server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka
    instance:
      preferIpAddress: true
    registerWithEureka: true
    fetchRegister: true
    
resilience4j:
  ratelimiter:
    instances:
      default:
        limit-for-period: 2
        limit-refresh-period: 10s
  retry:
    instances:
      default:
        max-attempts: 3
        wait-duration: 1s
  circuit-breaker:
    instances:
      default:
        falhe-rate-threshold: 40

spring:
  application:
    name: diets-groups-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/db_nutrition?createDatabaseIfNotExist=true&serverTimezone=America/Sao_Paulo&useSSl=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Brazil/East
    serialization:
      FAIL_ON_EMPTY_BEANS: false
      
  # flyway:
  #   url: jdbc:mysql://localhost:3306
  #   schemas: db_nutrition
  #   user: root
  #   password: root 



    
