server:
  port: 8888
spring:
  application:
    name: easediet-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/andreiflancanova/Easediet-Config-Server
          force-pull: true
          default-label: main
          search-paths:
          - 'easediet-config*'
management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings,refresh
