server:
  port: 8888
spring:
  application:
    name: easediet-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/andreiflancanova/Easediet-Config-Server
          #username: username
          #password:
          default-label: main
          search-paths:
          - 'easediet-config*'
        
