INSERT INTO `tb_diet` (`id`, 
`breakfast_fruit`, 
`breakfast_liquid`, 
`breakfast_solid`,
`calories_total_amount`, 
`diet_group_id`, 
`dinner_protein`, 
`dinner_salad`, 
`dinner_side_dish`,
`lunch_protein`, 
`lunch_salad`, 
`lunch_side_dish`, 
`name`, 
`nutritionist_id`) VALUES (
    'fb7b5541-1cab-4b4b-8ec2-1931f357a07c',
    'maçã',
    'Suco de Laranja',
    '2 torradas',
    1200,
    null,
    'Peito de frango',
    'Tomate com Alface',
    'Arroz Integral',
    'Filé de Peixe',
    'Agrião com Rúcula',
    'Arroz e Feijão',
    'Fitness',
    '1a07be34-4a55-494b-a68d-dddcc40944e2'
);